version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secret_santa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/secret_santa
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env

volumes:
  postgres_data: